/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class SmartAirConditioner {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('deviceId', 'IntAutoIncrement');
        fieldTypeMap.set('deviceName', 'String');
        fieldTypeMap.set('userId', 'String');
        fieldTypeMap.set('isOn', 'Boolean');
        fieldTypeMap.set('mode', 'String');
        fieldTypeMap.set('temperature', 'Integer');
        return fieldTypeMap;
    }

    getClassName() {
        return 'SmartAirConditioner';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('deviceId');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        indexList.push('userId');
        indexList.push('deviceName');
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setDeviceId(deviceId) {
        this.deviceId = deviceId;
    }

    getDeviceId() {
        return this.deviceId;
    }

    setDeviceName(deviceName) {
        this.deviceName = deviceName;
    }

    getDeviceName() {
        return this.deviceName;
    }

    setUserId(userId) {
        this.userId = userId;
    }

    getUserId() {
        return this.userId;
    }

    setIsOn(isOn) {
        this.isOn = isOn;
    }

    getIsOn() {
        return this.isOn;
    }

    setMode(mode) {
        this.mode = mode;
    }

    getMode() {
        return this.mode;
    }

    setTemperature(temperature) {
        this.temperature = temperature;
    }

    getTemperature() {
        return this.temperature;
    }
}

module.exports = {SmartAirConditioner}