/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class SmartLamp {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('deviceId', 'IntAutoIncrement');
        fieldTypeMap.set('userId', 'String');
        fieldTypeMap.set('deviceName', 'String');
        fieldTypeMap.set('isOn', 'Boolean');
        fieldTypeMap.set('coordX', 'Double');
        fieldTypeMap.set('coordY', 'Double');
        fieldTypeMap.set('isDeleted', 'Boolean');
        return fieldTypeMap;
    }

    getClassName() {
        return 'SmartLamp';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('deviceId');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        indexList.push('userId');
        indexList.push('deviceId');
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setDeviceId(deviceId) {
        this.deviceId = deviceId;
    }

    getDeviceId() {
        return this.deviceId;
    }

    setUserId(userId) {
        this.userId = userId;
    }

    getUserId() {
        return this.userId;
    }

    setDeviceName(deviceName) {
        this.deviceName = deviceName;
    }

    getDeviceName() {
        return this.deviceName;
    }

    setIsOn(isOn) {
        this.isOn = isOn;
    }

    getIsOn() {
        return this.isOn;
    }

    setCoordX(coordX) {
        this.coordX = coordX;
    }

    getCoordX() {
        return this.coordX;
    }

    setCoordY(coordY) {
        this.coordY = coordY;
    }

    getCoordY() {
        return this.coordY;
    }

    setIsDeleted(isDeleted) {
        this.isDeleted = isDeleted;
    }

    getIsDeleted() {
        return this.isDeleted;
    }
}

module.exports = {SmartLamp}